services:
  pgdb:
    image: postgres
    restart: unless-stopped
    container_name: pgdb_container
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/postgresql/data

  backend_app:
    depends_on:
      - pgdb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    stdin_open: true
    tty: true

  frontend_app:
    depends_on:
      - pgdb
      - backend_app
    build: ./react_frontend
    volumes:
      - ./react_frontend:/app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001/api/
      - PORT=3000
    stdin_open: true
    tty: true

volumes:
  db:
