version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
    command: npm run dev
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: postgres_container 
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgres

volumes:
  db_data:
